apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80        # port interne Kubernetes
      targetPort: 80  # port dans le container
      nodePort: 30002 # port sur la VM pour accéder depuis le navigateur
