apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  selector:
    app: uptime-kuma
  type: NodePort
  ports:
    - protocol: TCP
      port: 3001        # port interne du service
      targetPort: 3001  # port container
      nodePort: 30003   # port sur la VM pour accéder depuis le navigateur
